"""empty message

Revision ID: 42ff4ed15a4e
Revises: 4f47397abc2e
Create Date: 2018-01-10 16:43:19.579000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ff4ed15a4e'
down_revision = '4f47397abc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlement', sa.Column('number', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlement', 'number')
    # ### end Alembic commands ###
