"""empty message

Revision ID: 1c5aa4cce2c0
Revises: 5607a466319d
Create Date: 2018-01-09 22:05:36.650000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c5aa4cce2c0'
down_revision = '5607a466319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
