"""empty message

Revision ID: 5607a466319d
Revises: 78cef33b6bda
Create Date: 2018-01-09 20:30:11.888000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5607a466319d'
down_revision = '78cef33b6bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
