"""empty message

Revision ID: 6534813f46a2
Revises: d8da1d01a562
Create Date: 2018-01-07 17:08:33.113000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6534813f46a2'
down_revision = 'd8da1d01a562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookinformation', sa.Column('classfication', sa.String(length=50), nullable=False))
    op.add_column('bookinformation', sa.Column('date', sa.String(length=50), nullable=False))
    op.add_column('bookinformation', sa.Column('isbn', sa.String(length=50), nullable=False))
    op.add_column('bookinformation', sa.Column('press', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookinformation', 'press')
    op.drop_column('bookinformation', 'isbn')
    op.drop_column('bookinformation', 'date')
    op.drop_column('bookinformation', 'classfication')
    # ### end Alembic commands ###
