"""empty message

Revision ID: 78cef33b6bda
Revises: 6534813f46a2
Create Date: 2018-01-09 17:10:22.486000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cef33b6bda'
down_revision = '6534813f46a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookinformation', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookinformation', 'create_time')
    # ### end Alembic commands ###
